version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
 container_name: mailhog
    restart: always
    image: mailhog/mailhog:latest

    ports:
        -'8025:8025'
        -'1025:1025'

  # mailer:
  #   image: schickling/mailcatcher
  #   ports: [1025, 1080]
###< symfony/mailer ###
